apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- cronjob.yaml

configMapGenerator:
- name: worker-config
  literals:
  - PROCESSING_DELAY_SECONDS=2
  - PAYMENT_FAILURE_RATE=0.15
  - STALE_HOLD_MINUTES=15