apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - cancel-stale-cronjob.yaml
  - networkpolicy.yaml

secretGenerator:
  - name: hotel-secrets
    envs:
      - secrets.env

labels:
  - pairs:
      app.kubernetes.io/part-of: hotel-booking
    includeSelectors: false
