apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hotel-staging

resources:
- ../../base
- namespace.yaml
- postgres-externalname.yaml

configMapGenerator:
  - name: shared-config
    behavior: merge
    literals:
      - DB_SSLMODE=require
      - DB_USER=postgres.csrchajfnyjvgkwvtbuj
      - DB_NAME=postgres

secretGenerator:
  - name: db-credentials
    behavior: merge
    envs:
      - secrets.env

patches:
  - target:
      kind: Deployment
      name: "api|worker|frontend"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2